### ISSUE TITLE
Video doesn't play, black screen

### ISSUE THREAD

**Issue by wixerzp** [alex-free/video2dreamcastdisc#3]
I am using GDEMU, default settings, I just dragged the video on to the .bat file.

**Comment by alex-free** [comment]
> I am using GDEMU, default settings, I just dragged the video on to the .bat file.

Interesting, I don't have a gdemu to test. Is this the case with all video files you try? Does the same file work on a Dreamcast emulator?

**Comment by wixerzp** [comment]
I have now tried it with other video files and they are working just fine. :) A difference between those files and the non-working one is that the non-working one is very small, 2.8 MiBs whereas the other ones are 40-300 MiBs. The files don't work on an Emulator.

**Comment by alex-free** [comment]
> I have now tried it with other video files and they are working just fine. :) A difference between those files and the non-working one is that the non-working one is very small, 2.8 MiBs whereas the other ones are 40-300 MiBs. The files don't work on an Emulator. 

Oh, 2.8 MBs sounds like the video conversion failed. Is there any way you could copy the entire output of the program and upload it as a .txt file here?

**Comment by wixerzp** [comment]
[output.txt](https://github.com/alex-free/video2dreamcastdisc/files/13301980/output.txt)
Sure

**Comment by alex-free** [comment]
> [output.txt](https://github.com/alex-free/video2dreamcastdisc/files/13301980/output.txt) Sure

Found the issue:

MPEG-1/2 does not support 15/1 fps
[vost#0:0/mpeg1video @ 00000261593604c0] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Invalid argument
[out#0/mpeg1video @ 000002615901eec0] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
Conversion failed!

If you can re-encode the source file from 15fps to 30fps it should be fine.  Is this file really 15fps?

**Comment by temagram** [comment]
Ah, that makes sense. The video is indeed 15fps. Thank you!
